
export const NOUNS_DICT = [
	'salmon', 'tuna', 'avocado', 'cucumber', 'shrimp', 'crab', 'eel', 'unagi', 'tobiko', 'masago', 'nori', 'rice', 'seaweed', 'wasabi', 'soy sauce', 'ginger', 'tempura', 'California roll', 'Philadelphia roll', 'spicy tuna roll', 'dragon roll', 'rainbow roll', 'maki', 'nigiri', 'sashimi', 'sushi rice', 'sushi grade', 'roll', 'hand roll', 'temaki', 'poke', 'rice ball', 'triangle', 'umeboshi', 'pickled plum', 'furikake', 'sesame seeds', 'snack', 'lunch', 'creation', 'texture', 'bite', 'plate', 'art', 'shiso leaf', 'tarako', 'kombu', 'kelp', 'okaka', 'flakes', 'tsukemono', 'topping', 'filling', 'wrap', 'mayo', 'eel sauce', 'mango', 'paste', 'pickle', 'kanikama', 'tako', 'sake', 'hamachi', 'tai', 'maguro', 'ebi', 'ikura', 'oshinko', 'hosomaki', 'gunkanmaki', 'chirashizushi', 'oshizushi', 'kapppamaki', 'inarizushi', 'futomaki', 'uramaki', 'onigiri', 'spider roll', 'Alaska roll', 'Boston roll', 'caterpillar roll', 'firecracker roll', 'volcano roll', 'vegetable roll', 'dynamite roll', 'jackpot roll', 'memo', 'task', 'chore', 'errand', 'plan', 'ponzu', 'octopus', 'roe', 'amadai', 'anago', 'awabi', 'aji', 'chu-toro', 'gari', 'hamaguri', 'hotate', 'ika', 'iwashi', 'kamasu', 'kazunoko', 'kome', 'koshu', 'miso shiru', 'oboro', 'otoshi', 'shoyu', 'suzuki', 'tamago', 'toro', 'tofu', 'tekkamaki'
];

export const NOUNS_DICT_JA = [
	'サーモン', 'マグロ', 'アボカド', 'キュウリ', 'エビ', 'カニ', 'ウナギ', 'ウナギ', 'トビコ', '真砂', '海苔', 'ご飯', '海藻', 'ワサビ', '醤油', '生姜', '天ぷら', 'カリフォルニアロール', 'フィラデルフィアロール', 'スパイシーツナロール', 'ドラゴンロール', 'レインボーロール', '巻き', '握り', '刺身', '寿司飯', '寿司用', '巻き', '手巻き', '手巻き', 'ポキ', 'おにぎり', '三角', '梅干し', '梅干し', 'ふりかけ', 'ごま', 'おやつ', 'ランチ', '創作', '食感', '一口', '皿', 'アート', '大葉', 'たらこ', '昆布', '昆布', 'おかか', 'フレーク', '漬物', 'トッピング', '餡',  'ラップ', 'マヨ', 'うなぎのたれ', 'マンゴー', 'ペースト', '漬物', 'カニカマ', 'たこ', '日本酒', 'はまち', 'たい', 'まぐろ', 'えび', 'いくら', 'おしんこ', '細巻き', '軍艦巻き', 'ちらし寿司',  '押し寿司',  'かっぱ巻き', 'いなり寿司', '太巻き', 'うら巻き', 'おにぎり', 'スパイダーロール', 'アラスカロール', 'ボストンロール', 'キャタピラーロール', '爆竹ロール', '火山ロール', '野菜ロール', 'ダイナマイトロール', 'ジャックポットロール', 'メモ',  '仕事', '雑用', '用事', '計画', 'ポン酢', 'タコ', 'イクラ', 'アマダイ', 'アナゴ', 'アワビ', 'アジ', '中トロ', 'ガリ', 'ハマグリ', 'ホタテ', 'イカ', 'イワシ', 'かます', 'かずのこ',  '米', '甲州',  '味噌汁', 'おぼろ', 'お通し', '醤油', 'スズキ', '玉子', 'トロ', '豆腐', '鉄火巻'
];

export const NOUNS_DICT_ZH = [
	'三文鱼', '金枪鱼', '牛油果', '黄瓜', '虾', '螃蟹', '鳗鱼', '飞鱼籽', '真子', '海苔', '米饭', '海藻', '芥末', '酱油', '姜', '天妇罗', '加州卷', '费城卷', '辣金枪鱼卷', '龙卷', '彩虹卷', '卷寿司', '握寿司', '刺身', '寿司米', '寿司用饭', '卷寿司', '手卷', '手卷', 'Poke', '饭团', '三角形', '梅干', '梅干', '拌饭香松', '芝麻', '小吃', '午餐', '创意', '口感', '咬一口', '盘子', '艺术', '紫苏', '鳕鱼子', '昆布', '昆布', 'Okaka', '薄片', '沾物', '浇头', '安', '卷', '蛋黄酱', '鳗鱼酱', '芒果', '酱', '沾物', '蟹镰', '章鱼', '清酒', '滨町', '金枪鱼', '虾', '井仓', '阿辛科', '细卷',  '军舰卷', '散寿司', '押寿司', '河童卷', '稻荷寿司', 'Futomaki', '浦卷', '饭团', '蜘蛛卷', '阿拉斯加卷', '波士顿卷', '毛毛虫卷', '爆竹卷', '火山卷', '蔬菜卷', '炸药卷', '大奖卷',  '备忘录', '工作', '零工', '差事', '计划', '柚子', '章鱼', '鲑鱼子', '方头鱼', '海鳗', '鳗鱼', '鲍鱼', '竹荚鱼', '中肥金枪鱼', '加里', '蛤', '扇贝', '鱿鱼', '沙丁鱼', '梭子鱼', '马子', '米饭', '甲州', '味噌汤', 'Oboro', '开胃菜', '酱油', '铃木', '鸡蛋',  '肥金枪鱼', '豆腐', '铁卷'
]

export const ADJECTIVES_DICT = [
	'Zen', 'Serene', 'Chaotic', 'Busy', 'Non-essential', 'Bottom-priority', 'Minute', 'Genius', 'Simple', 'Too much', 'Umami', 'Unbelievable', 'Delicious', 'Coastal', 'Ocean', 'Misty', 'Spicy', 'Tangy', 'Savory', 'Delicate', 'Fresh', 'Vibrant', 'Colorful', 'Artistic', 'Whimsical', 'Dreamy', 'Ninja', 'Sumo', 'Karate-chop', 'Tiny', 'Flavor', 'Explosive', 'Pocket', 'Rolling', 'Zen', 'Crabby', 'Pickled', 'Ginger', 'Patty', 'Rice-y', 'Get it done', 'Tackle this', 'Knock out', 'Wrap up', 'Sort out', 'Deal with', 'Time to', 'Top priority', 'Best', 'High importance', 'Quick win', 'Short and sweet', 'Tough nut', 'Breezing', 'Smooth', 'Bumpy', 'Gentle', 'Super duper', 'Radically cool', 'Totally awesome', 'Don\'t forget', 'Pretty much', 'Sort of', 'Maybe later', 'In a jiffy', 'ASAP', 'No sweat', 'Easy peasy', 'Let\'s roll', 'Seriously though', 'Almost done', 'Work smarter, not', 'Level up', 'Full steam ahead', 'Keep calm', 'Never give up', 'Stay focused', 'New beginnings', 'Turning point', 'Finishing touch', 'Home stretch', 'Clean slate', 'Challenging', 'Rice overload', 'A little fishy', 'Pefecting the', 'Journey to the', 'Mysterious', 'Reserved for', 'Confidential', 'Silly', 'Stellar', 'Totally', 'Mega', 'Amazing', 'Awesome', 'Chewy', 'Crunchy', 'Silky', 'Rough', 'Mild', 'Gloomy', 'Sunny', 'Sweet', 'Peaceful', 'Crisp', 'Teeny-tiny', 'Humongous', 'Gigantic', 'Massive', 'Incomplete', 'Long-term', 'Short-term', 'Hold on,', 'Urgent', 'Raw', 'Delightful', 'Feast on', 'Adventurous', 'Snappy'
];