
export const LOCALIZE_TERMS = [
	{ key: 'noto maki', en: 'noto maki', ja: 'ノート 巻', zh: '笔记卷' },
	{ key: 'btn-cancel', en: 'Cancel', ja: 'キャンセル', zh: '取消' },
	{ key: 'btn-create', en: 'Cancel', ja: '作成する', zh: '创建' },
	{ key: 'btn-rename', en: 'Rename', ja: '名前を変更', zh: '重命名' },
	{ key: 'btn-delete', en: 'Delete', ja: '消去', zh: '删除' },
	{ key: 'btn-delete_yes', en: 'Yes, delete!!!', ja: 'はい、削除!!!', zh: '是，删除！！！' },
	{ key: 'btn-delete_no', en: 'No, keep it', ja: 'いいえ、保つ', zh: '不，保留' },
	{ key: 'btn-delete_got', en: 'Got it', ja: 'わかった', zh: '知道了' },
	{ key: 'btn-move_up', en: 'Move up', ja: '上に移動', zh: '向上移动' },
	{ key: 'btn-move_down', en: 'Move down', ja: '下に移動', zh: '向下移动' },
	{ key: 'btn-note_new', en: 'New note', ja: '「ノート」を追加', zh: '添加笔记' },
	{ key: 'btn-note_delete', en: 'Delete note', ja: '「ノート」を削除', zh: '删除笔记' },
	{ key: 'h-create_tab', en: 'Create a new tab', ja: '新しい「ノート」を作成', zh: '创建新标签' },
	{ key: 'h-delete', en: 'Delete *', ja: '「*」を削除しますか?', zh: '删除「*」' },
	{ key: 'h-delete_to', en: 'Uh oh. Cannot roll away!', ja: '行っちゃダメだよ！', zh: '滚不走哦！' },
	{ key: 'h-delete_no', en: 'Stop right there!', ja: 'ちょっと待って！', zh: '且慢！' },
	{ key: 't-untitled_tab', en: 'Untitled tab', ja: '無題 ラベル', zh: '未命名标签' },
	{ key: 't-untitled_tab_ph', en: 'e.g., Personal', ja: '例：個人メモ', zh: '例如：个人笔记' },
	{ key: 't-untitled_note_ph', en: 'Untitled note', ja: '無題 ノート', zh: '未命名笔记' },
	{ key: 't-untitled_heading_ph', en: 'Type heading...', ja: 'タイトルを入力してください...', zh:'输入标题...' },
	{ key: 't-last_updated', en: 'Last updated: ', ja: '前回の更新時: ', zh:'上次更新：' },
	{ key: 't-today_at', en: 'Today at *', ja: '今日の*', zh:'今天*' },
	{ key: 't-yesterday_at', en: 'Yesterday at *', ja: '昨日の*', zh: '昨天*' },
	{ key: 't-this_year_at', en: '*', ja: '今年*日', zh: '今年*号' },
	{ key: 't-delete_label', en: 'Be careful with this action.', ja: 'ご注意ください。', zh: '请注意。' },
	{ key: 't-delete_tab_more', en: 'Deleting this tab will delete all notes associated with it!!!', ja: 'この「ラベル」を削除すると、それに関連付けられているすべての「ノート」が削除されます!!!', zh: '删除此标签将删除与其相关的所有笔记！！！' },
	{ key: 't-delete_to_label', en: 'You cannot delete your only tab.', ja: '固有の「ラベル」を削除することはできません。', zh: '您无法删除您的唯一标签。' },
	{ key: 't-delete_to_more', en: 'Try adding a tab you really want and come back to delete this one to get it out of the way.', ja: '新しい「ラベル」を追加し、戻ってこの「ラベル」を削除します。', zh: '添加一个新的标签再回来删除此标签吧。' },
	{ key: 't-delete_no_label', en: 'You cannot delete your only note in this tab.', ja: 'この「ラベル」内の唯一の「ノート」は削除できません。', zh: '您无法删除此标签中唯一的笔记。' },
	{ key: 't-delete_no_more', en: 'Try adding a note you really want and come back to delete this one to get it out of the way.', ja: '新しい「ノート」を追加し、戻ってこの「ノート」を削除します。', zh: '添加一个新的笔记再回来删除此笔记吧。' },
	{ key: 'btn-save', en: 'Save', ja: '保存', zh: '保存' },
	{ key: 't-save_tip', en: 'Manual save for peace of mind', ja: '安心のための手動保存', zh: '手动保存，安心无忧' },
	{ key: 't-save_success', en: 'Saved successfully!', ja: '保存に成功しました!', zh: '保存成功！' },
];